title: Entry Page
context:
  bodyClass: entry-page
  title: Lorem Ipsum Dolor Sit Amet, Consectetur Adipiscing Elit
  subtitle: Mauris feugiat lorem nisl, ut bibendum purus finibus sed.
  time: January 1, 2017
  sectionTitle: Bibendum Purus Finibus
  authors:
    -
      headingLevel: 3
      headingImageLink: true
      title: Evan Minto
      description: Evan is the Editor-in-chief of Ani-Gamers, a freelance reviewer for Otaku USA Magazine, and a frequent anime convention panelist. You can read his ravings about anime, manga, games, politics, music, and more on Twitter @VamptVo.
      modifierClass: summary--staff
    -
      headingLevel: 3
      headingImageLink: true
      title: David Estrella
      description: David has been in the same room as people who write for anime magazines and websites.
      modifierClass: summary--staff
  topics:
    -
      subject: Posts
      link: true
    -
      subject: Anime
      link: true
    -
      subject: Manga
      link: true
    -
      subject: Video Games
      link: true
    -
      subject: Conventions
      link: true
    -
      subject: Otakon 2017
      link: true
    -
      subject: Masao Maruyama
      link: true
variants:
  -
    name: Magazine
    context:
      themeFile: /css/entry_themes/magazine.css
  -
    name: Magazine (Fancy)
    context:
      themeFile: /css/entry_themes/magazine_fancy.css
  -
    name: Magazine (Big)
    context:
      themeFile: /css/entry_themes/magazine_big.css
  -
    name: Multicolumn
    context:
      themeFile: /css/entry_themes/multicolumn.css
