title: Summary
context:
  headingLevel: 4
  title: Lorem Ipsum Dolor Sit Amet
  subtitle: In velit felis, facilisis pharetra rhoncus in, tincidunt eu libero.
  description: Phasellus eget lobortis augue. Suspendisse vestibulum nibh a facilisis convallis. Suspendisse eu urna sollicitudin nibh tristique efficitur.
variants:
  -
    name: Column
    context:
      headingLevel: 3
      subtitle: ''
      description: ''
      modifierClass: summary--column
