title: Suggested Entry
context:
  imageSmall: /images/Yuri-on-Ice.jpg
  imageLarge: /images/Yuri-on-Ice.jpg
  title: Yuri!!! on Ice Staff Discuss Sayo Yamamoto and Skating Animation
  timestamp: January 1, 2018
