title: Entry Search Result
context:
  headingLevel: 2
  title: Lorem Ipsum Dolor Sit Amet, Consectetur Adipiscing Elit
  subtitle: Mauris feugiat lorem nisl, ut bibendum purus finibus sed.
  description: By Evan Minto and David Estrella
  modifierClass: summary--entry-search-result
