title: Entry Header
context:
  authors:
    - Evan Minto
    - Ink
  timestamp: January 1, 2018
  title: Yuri!!! on Ice Staff Discuss Sayo Yamamoto and Skating Animation
variants:
  -
    name: Title Only
    context:
      authors: false
      timestamp: false
      title: About Us
