title: Staff Bio
context:
  name: Evan Minto
  jobTitle: Editor-in-Chief
  biography: Evan is the Editor-in-chief of Ani-Gamers, a freelance reviewer for Otaku USA Magazine, and a frequent anime convention panelist. You can read his ravings about anime, manga, games, politics, music, and more on Twitter @VamptVo.
